
<div class="reg_form">
    <form action="" method="post">
    <table class="admintable">
    	<tbody>
    		<tr>
    			<td class="key">Username<span class="req"> *</span></td>
    			<td><?php echo $this->element->username; ?></td>
    		</tr>
    		<tr>
    			<td class="key">Password<span class="req"> *</span></td>
    			<td><?php echo $this->element->password; ?></td>
    		</tr>
    		
    		<tr>
    			<td class="key">Xác nhận Password<span class="req"> *</span></td>
    			<td><?php echo $this->element->password_confirm; ?></td>
    		</tr>
        
    		<tr>
    			<td class="key">Họ và tên lót<span class="req"> *</span></td>
    			<td><?php echo $this->element->lastname; ?></td>
    		</tr>
    
            <tr>
    			<td class="key">Tên<span class="req"> *</span></td>
    			<td><?php echo $this->element->firstname; ?></td>
    		</tr>
    		
    		<tr>
    			<td class="key">Email<span class="req"> *</span></td>
    			<td><?php echo $this->element->email; ?></td>
    		</tr>
    		
    		<tr>
    			<td class="key">Điện thoại<span class="req"> *</span></td>
    			<td><?php echo $this->element->phone; ?></td>
    		</tr>
    		<tr>
    			<td class="key">Địa chỉ</td>
    			<td><?php echo $this->element->address; ?></td>
    		</tr>
    		<tr>
    			<td class="key"></td>
    			<td><input type="submit" name="" value=" Gửi " /></td>
    		</tr>
    	</tbody>
    </table>
    </form>
</div>