

<div class="reg_form">
    <form action="" method="post">
    <table class="admintable">
    	<tbody>
    		<tr>
    			<td class="key">Username<span class="req"> *</span></td>
    			<td><?php echo $this->element->username; ?></td>
    		</tr>
    		<tr>
    			<td class="key">Password<span class="req"> *</span></td>
    			<td><?php echo $this->element->password; ?></td>
    		</tr>
    		<tr>
    			<td class="key"></td>
    			<td><input type="submit" name="" value=" Đăng ký " /></td>
    		</tr>
    	</tbody>
    </table>
    </form>
</div>







