<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

</head>

<body>
<h1>An error accurred</h1>
<h2><?php echo $this->message; ?></h2>

<?php
if ('development' == APPLICATION_ENV) {
	?>
	<h3>Exception info:</h3>
	<p>
		<?php echo $this->exception->getCode(); ?>
		<b>Messages:</b> <?php echo $this->exception->getMessage(); ?>
	</p>
	<p>
		<b>File:</b> <?php echo $this->exception->getFile(); ?> - Line: <?php echo $this->exception->getLine(); ?>
	</p>
	<h3>Stack trace:</h3>
	<pre><?php echo $this->exception->getTraceAsString(); ?></pre>
	
	<h3>Request parameters</h3>
	<pre><?php var_dump($this->request->getParams()); ?></pre>
	<?php 	
} 
?>
</body>
</html>
