<table cellspacing="1" class="admintable">
    <tbody>
    
    <tr>
    <td class="key">Giá</td>
    <td><?php echo $this->element->price; ?></td></tr>
    
    <!-- 
    <tr>
    <td class="key">Số phòng ngủ</td>
    <td><?php echo $this->element->bedroom; ?></td></tr>
    
    <tr>
    <td class="key">Diện tích</td>
    <td><?php echo $this->element->area; ?></td></tr>
     -->
    <tr>
    <td class="key">Địa chỉ (Maps)</td>
    <td><?php echo $this->element->address; ?></td></tr>
    
    <tr>
    <td class="key">Intro</td>
    <td><?php echo $this->element->intro; ?></td></tr>
    
	</tbody>
</table>
<?php echo $this->element->facility; ?>
<?php echo $this->element->description; ?>