<table cellspacing="1" class="admintable">
    <tbody>
    
    <tr>
    <td class="key">Giá</td>
    <td><?php echo $this->element->price; ?></td></tr>
    
    <tr>
    <td class="key">Số phòng ngủ</td>
    <td><?php echo $this->element->bedroom; ?></td></tr>
    
    <tr>
    <td class="key">Diện tích</td>
    <td><?php echo $this->element->area; ?></td></tr>

	</tbody>
</table>
<?php echo $this->element->description; ?>