<fieldset class="adminform">
    <legend>Thông tin cơ bản</legend>
    <table cellspacing="1" class="admintable">
    	<tbody>
    		<tr>
    			<td class="key">Mã</td>
    			<td><?php echo $this->element->code; ?></td>
    		</tr>
    		<tr>
    			<td class="key">Tên</td>
    			<td><?php echo $this->element->name; ?></td>
    		</tr>
    
    		<tr>
    			<td class="key">Định danh (Alias)</td>
    			<td><?php echo $this->element->alias; ?></td>
    		</tr>
    
    		<tr>
    			<td class="key">Nhóm</td>
    			<td><?php echo $this->element->article_group; ?></td>
    		</tr>
    
    		<tr>
    			<td class="key">Kích hoạt</td>
    			<td><?php echo $this->element->publish; ?></td>
    		</tr>
    	</tbody>
    </table>

    
</fieldset>

<fieldset class="adminform">
	<legend>Tóm tắt</legend>
	
	<?php 
	echo $this->element->b_summarize;
	?>
</fieldset>

<fieldset class="adminform">
	<legend>Nội dung</legend>
	
	<?php 
	echo $this->element->b_content;
	?>
</fieldset>



