
<div class="row">
    <div class="l">Giá</div>
    <div class="r"><?php echo $this->element->price; ?></div>
</div>

<div class="row">
    <div class="l">Địa chỉ</div>
    <div class="r"><?php echo $this->element->address; ?></div>
</div>

<div class="row">
    <div class="l">Tiện ích</div>
    <div class="r"><?php echo $this->element->facility; ?></div>
</div>

<div class="row">
    <div class="l">Mô tả</div>
    <div class="r"><?php echo $this->element->description; ?></div>
</div>

