<fieldset class="adminform">
    <legend>Thông tin cơ bản</legend>
    <table cellspacing="1" class="admintable">
    	<tbody>
    		
    		<tr>
    			<td class="key">Tên</td>
    			<td><?php echo $this->element->name; ?></td>
    		</tr>
    
    		<tr>
    			<td class="key">Định danh (Alias)</td>
    			<td><?php echo $this->element->alias; ?></td>
    		</tr>
    
    		<tr>
    			<td class="key">Kích hoạt</td>
    			<td><?php echo $this->element->publish; ?></td>
    		</tr>
    	</tbody>
    </table>

    
</fieldset>





