<fieldset class="adminform">
    <legend>Thông tin cơ bản</legend>
    <table cellspacing="1" class="admintable">
    	<tbody>
    		<tr>
    			<td class="key">Username</td>
    			<td><?php echo $this->element->username; ?></td>
    		</tr>
    		<tr>
    			<td class="key">Password</td>
    			<td><?php echo $this->element->password; ?></td>
    		</tr>
    		
    		<tr>
    			<td class="key">Xác nhận Password</td>
    			<td><?php echo $this->element->password_confirm; ?></td>
    		</tr>
        
    		<tr>
    			<td class="key">Họ và tên lót</td>
    			<td><?php echo $this->element->lastname; ?></td>
    		</tr>
    
            <tr>
    			<td class="key">Tên</td>
    			<td><?php echo $this->element->firstname; ?></td>
    		</tr>
    		
    		<tr>
    			<td class="key">Email</td>
    			<td><?php echo $this->element->email; ?></td>
    		</tr>
    		
    		<tr>
    			<td class="key">Điện thoại</td>
    			<td><?php echo $this->element->phone; ?></td>
    		</tr>
    		<tr>
    			<td class="key">Địa chỉ</td>
    			<td><?php echo $this->element->address; ?></td>
    		</tr>
    		<tr>
    			<td class="key">Nhóm</td>
    			<td><?php echo $this->element->user_group_id; ?></td>
    		</tr>
    
    		<tr>
    			<td class="key">Kích hoạt</td>
    			<td><?php echo $this->element->publish; ?></td>
    		</tr>
    	</tbody>
    </table>

    
</fieldset>





